### ISSUE TITLE
Orientace

### ISSUE THREAD

**Issue by Prochyxd** [Prochyxd/MojeRande#2]
Je tam jak homosexualita tak lesbictvi chybi gej, nejlepe dat homosexualni orientaci a odstranit lesbictvi

**Comment by matyas-zavora** [comment]
Opravdu tohle chceme udělat? Museli bychom potom dělat zbytečně podmínky navíc při hledání partnera. Taky bychom museli přidat pohlaví a do toho se nechci vměšovat...

npř.: Je gay, ale je muž -> hledáme muže
