### ISSUE TITLE
 Email již existuje!  Prosím, zvolte jiný email.  Zkuste to znovu.

### ISSUE THREAD

**Issue by Prochyxd** [Prochyxd/MojeRande#3]
Při změně napříkald profilového obrázku je automaticky zadaný email v kolonce email, když uživatel udělá změnu v profilu, změna se sice provede ale vypíše se :
Email již existuje!

Prosím, zvolte jiný email.

Zkuste to znovu.

**Comment by Prochyxd** [comment]
Když máš v prohléžeči uložené přihlašovací údaje tak se tam totiž vloží automaticky do kolonky emailu a hesla. Když se odhlásíš a přihlásíš jako jiný uživatel tak se tam stejně vloží ty údaje toho účtu který je uložený v prohlížeči

**Comment by matyas-zavora** [comment]
PICNIC
